### ISSUE TITLE
ubuntukylin-icon-theme: Check if the custom plugin can inherit from snapcraft.plugins.copy.CopyPlugin

### ISSUE THREAD

**Issue by dholbach** [ubuntu/snappy-playpen#117]
It looks like the vast majority of `ubuntukylin-icon-theme/parts/plugins/copy_and_edit.py` is copied from snapcraft's `snapcraft/plugins/copy.py`. Could we make it inherit from `snapcraft.plugins.copy.CopyPlugin` instead?

**Comment by didrocks** [comment]
I think it should rather use another plugin, which edits files directly in stage/ directory. I'll have a good at that next week.

**Comment by didrocks** [comment]
This is now done
