### ISSUE TITLE
vlc: Check if the custom plugin can inherit snapcraft's snapcraft.plugins.autotools.AutotoolsPlugin

### ISSUE THREAD

**Issue by dholbach** [ubuntu/snappy-playpen#118]
Check if the custom plugin can inherit snapcraft's `snapcraft.plugins.autotools.AutotoolsPlugin` this would avoid code getting out of date.

**Comment by didrocks** [comment]
Nice that our plans are matching up! I'm already workink on it as I did it for Atom ;)
