### ISSUE TITLE
atom crashes on startup

### ISSUE THREAD

**Issue by rednoah** [ubuntu/snappy-playpen#129]
The `atom` snap doesn't seem to work. Crashes on startup as follows:
```
$ atom
$ /snap/atom/x1/bin/atom: line 108: /usr/bin/nohup: Permission denied
```

Same issue when using the `atom-cwayne` snap available in the app store. IMHO it's more 🔴  than ✅  at this point. :D

**Comment by dplanella** [comment]
It works for me here, just remember that for now you need to install it using `--devmode`

**Comment by rednoah** [comment]
I see. I guess this one predates `confinement: devmode`.
