### ISSUE TITLE
No application binary in snap

### ISSUE THREAD

**Issue by pbek** [ubuntu/snappy-playpen#145]
I wanted to create a snap for <http://github.com/pbek/QOwnNotes> and the build went quite well and the snap was created, but it seems the the built binary wasn't found and that's why it wasn't included in the snap (that can be installed sucessfully).

`snapcraft.yml` I created: <https://github.com/pbek/QOwnNotes/blob/develop/build-systems/snap/snapcraft.yaml>

Commands I executed:
```
cd ~/Code/_internal/QOwnNotes/build-systems/snap
snapcraft build
sudo snap install qownnotes_16.07.2_amd64.snap
```

These are the lines of the output near the end of the `snapcraft build`:

```
make install INSTALL_ROOT=/home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install
install -m 755 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/QOwnNotes /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/bin/
install: Aufruf von stat für '/home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/QOwnNotes' nicht möglich: Datei oder Verzeichnis nicht gefunden
Makefile:1981: die Regel für Ziel „install_target“ scheiterte
make: [install_target] Fehler 1 (ignoriert)
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/QOwnNotes.desktop /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/applications/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_de.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_en.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_es.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_fr.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_hu.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_it.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_ja.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_nl.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_pl.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_pt.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_ru.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
install -m 644 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/languages/QOwnNotes_zh.qm /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/QOwnNotes/languages/
cp -f -R /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/images/icons/128x128 /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/icons/hicolor/
cp -f -R /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/images/icons/16x16 /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/icons/hicolor/
cp -f -R /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/images/icons/24x24 /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/icons/hicolor/
cp -f -R /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/images/icons/256x256 /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/icons/hicolor/
cp -f -R /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/images/icons/32x32 /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/icons/hicolor/
cp -f -R /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/images/icons/48x48 /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/icons/hicolor/
cp -f -R /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/images/icons/512x512 /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/icons/hicolor/
cp -f -R /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/images/icons/64x64 /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/icons/hicolor/
cp -f -R /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/images/icons/96x96 /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/icons/hicolor/
cp -f -R /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/images/icons/scalable /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/share/icons/hicolor/
```

Can anyone imagine what went wrong?

This is the qmake project file: <https://github.com/pbek/QOwnNotes/blob/develop/src/QOwnNotes.pro>
Note that it will create a binary `QOwnNotes`, but the name of the snapcraft is `qownnotes`. Is that a problem?

This line in the output produces a `not found` error:
```
install -m 755 -p /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/src/QOwnNotes /home/omega/Code/_internal/QOwnNotes/build-systems/snap/parts/qownnotes/install/usr/bin/
```

**Comment by pbek** [comment]
I found a `QOwnNotes` binary in `parts/qownnotes/build`, but snapcraft tries to install it from `parts/qownnotes/src/QOwnNotes` (according to the generated QOwnNotes make file).

Can I tell snapcraft to use the binary `parts/qownnotes/build/QOwnNotes`?

**Comment by dholbach** [comment]
In the generated `Makefile` during the build it looks like for `QOwnNotes` (and other files like the `.desktop` file in `.` and not in `./parts/qownnotes/build`. I'm not quite sure where the problem comes from and pinged @kyrofa and @sergiusens about it.

**Comment by pbek** [comment]
Thank you @dholbach!
Maybe @popey can help, I started to create a snap after watching his video <https://www.youtube.com/watch?v=K0IzxsIFjJY> ;)

**Comment by kyrofa** [comment]
@pbek @dholbach I'm not sure why this is happening, but I suspect an issue with qmake's out-of-source build support. It doesn't seem to be working in this case, and I'm not sure why. @pbek use this as a local plugin for now:

```python3
# -*- Mode:Python; indent-tabs-mode:nil; tab-width:4 -*-
#
# Copyright (C) 2016 Canonical Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""The qmake plugin is useful for building qmake-based parts.

These are projects that are built using .pro files.

This plugin uses the common plugin keywords as well as those for "sources".
For more information check the 'plugins' topic for the former and the
'sources' topic for the latter.

Additionally, this plugin uses the following plugin-specific keywords:

    - options:
      (list of strings)
      additional options to pass to the qmake invocation.
    - qt-version:
      (enum, 'qt4' or 'qt5')
      Version of Qt to use with qmake.
    - project-files:
      (list of strings)
      list of .pro files to pass to the qmake invocation.
"""

import os
import shutil

import snapcraft
from snapcraft import common


class QmakePlugin(snapcraft.BasePlugin):

    @classmethod
    def schema(cls):
        schema = super().schema()
        schema['properties']['options'] = {
            'type': 'array',
            'minitems': 1,
            'uniqueItems': True,
            'items': {
                'type': 'string',
            },
            'default': [],
        }
        schema['properties']['qt-version'] = {
            'enum': ['qt4', 'qt5'],
        }
        schema['properties']['project-files'] = {
            'type': 'array',
            'minitems': 1,
            'uniqueItems': True,
            'items': {
                'type': 'string',
            },
            'default': [],
        }

        # Qt version must be specified
        schema['required'].append('qt-version')

        # Inform Snapcraft of the properties associated with building and
        # pulling so it can mark those steps dirty if they change in the YAML.
        schema['build-properties'].append('options')
        schema['pull-properties'].append('qt-version')

        return schema

    def __init__(self, name, options, project):
        super().__init__(name, options, project)

        self.build_packages.append('make')
        if self.options.qt_version == 'qt5':
            self.build_packages.extend(['qt5-qmake', 'qtbase5-dev'])
        elif self.options.qt_version == 'qt4':
            self.build_packages.extend(['qt4-qmake', 'libqt4-dev'])
        else:
            raise RuntimeError('Unsupported Qt version: {!r}'.format(
                self.options.qt_version))

    def build(self):
        super().build()

        env = self._build_environment()

        sources = []
        if self.options.project_files:
            sources = [os.path.join(self.sourcedir, project_file)
                       for project_file in self.options.project_files]

        self.run(['qmake'] + self._extra_config() + self.options.options +
                 sources, env=env)

        self.run(['make', '-j{}'.format(
            self.project.parallel_build_count)], env=env)

        self.run(['make', 'install', 'INSTALL_ROOT=' + self.installdir],
                 env=env)

    def _extra_config(self):
        extra_config = []

        for root in [self.installdir, self.project.stage_dir]:
            paths = common.get_library_paths(root, self.project.arch_triplet)
            for path in paths:
                extra_config.append("LIBS+=\"-L{}\"".format(path))

            paths = common.get_include_paths(root, self.project.arch_triplet)
            for path in paths:
                extra_config.append("INCLUDEPATH+=\"{}\"".format(path))

        return extra_config

    def _build_environment(self):
        env = os.environ.copy()
        env['QT_SELECT'] = self.options.qt_version

        return env
```

I'll upstream that.

**Comment by pbek** [comment]
Thank you for helping, @kyrofa!

I created your qmake plugin (thanks a lot!) and did a `snapcraft clean && sanapcraf build`.
The `make install` works now!

```
install -m 755 -p /home/omega/Code/_test/QOwnNotes-Snapcraft/parts/qownnotes/build/QOwnNotes /home/omega/Code/_test/QOwnNotes-Snapcraft/parts/qownnotes/install/usr/bin/
```

The binary was present at `parts/qownnotes/install/usr/bin/QOwnNotes`.
But I still could not find an application binary in the snap.

**Comment by kyrofa** [comment]
@pbek note the case: QOwnNotes. Your command is lower-case: `command: desktop-launch qownnotes`. Perhaps try `command: desktop-launch QOwnNotes`.

**Comment by kyrofa** [comment]
@pbek also, you probably know this but I want to throw it out there just in case: `snapcraft build` does not create a snap. You need to use `snapcraft snap` or just `snapcraft` to do that.

**Comment by pbek** [comment]
@kyrofa, thank you for the hints! I'm testing them currently.

**Comment by pbek** [comment]
meanwhile: I would like to modify a header file from the downloaded source archive before building it. Is that possible in the snapcraft.xml?

**Comment by pbek** [comment]
@kyrofa, the binary is now present inside the mounted snap at `./usr/bin/QOwnNotes` and can be executed directly, but calling `qownnotes` still just outputs `aa_change_onexec failed with -1. errmsg: No such file or directory`.

I have tried both `desktop-launch QOwnNotes` and `desktop-launch usr/bin/QOwnNotes` as `command` in the snapcraft.xml.

**Comment by kyrofa** [comment]
@pbek what distro are you running? Can I see the output of `cat /etc/os-release`, please?

**Comment by pbek** [comment]
@kyrofa, thank you for helping!

```
$ cat /etc/os-release
NAME="KDE neon"
VERSION="5.7"
ID=neon
ID_LIKE=ubuntu debian
PRETTY_NAME="KDE neon User Edition 5.7"
VERSION_ID="16.04"
HOME_URL="http://neon.kde.org/"
SUPPORT_URL="http://neon.kde.org/"
BUG_REPORT_URL="http://bugs.kde.org/"
UBUNTU_CODENAME=xenial
```

**Comment by kyrofa** [comment]
@pbek ah, I'm afraid that's bug [#1593255](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1593255). It's fixed in 2.0.10, which is making its way through the SRU process now. Hang tight, I'm sorry!

**Comment by pbek** [comment]
These are my configuration files right now: <https://github.com/pbek/QOwnNotes/tree/develop/build-systems/snap>

**Comment by pbek** [comment]
Oh, thank you for letting me know, @kyrofa. Will there be an update for snap 2.0.10 in Ubuntu?

And I would like to modify a header file from the downloaded source archive (or copy one file from the archive over the current header file) before building it. Is that possible in the snapcraft.xml?

**Comment by kyrofa** [comment]
> Will there be an update for snap 2.0.10 in Ubuntu?

Oh yes, subscribe to [the SRU bug](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1597329) so you can know when to update.

Regarding patching, no, that's not currently supported within snapcraft. Currently the recommended way to do that is to have a fork with the patch applied.

**Comment by pbek** [comment]
> SRU bug

Thank you, I now did.

> patching

That's not very convenient. :) Do you know if there are any plans to implement support for running shell commands or copying files before the build process (like for Arch PKGBUILD, AUR, SlackBuild or Gentoo)?

**Comment by pbek** [comment]
And (since you are a never ending source of knowledge) an other question, @kyrofa. Can I build snaps on Launchpad? I haven't found anything about that, but I think I heard it works... So I'm asking myself how.

**Comment by kyrofa** [comment]
Indeed you can, [check this out](https://kyrofa.com/posts/building-your-snap-on-device-there-s-a-better-way).

**Comment by pbek** [comment]
Wonderful, thank you very much, @kyrofa!

**Comment by pbek** [comment]
@kyrofa: the build on Lauchpad didn't went so well for me. :)
First I had to remove the `confinement` property, because Launchpad complained that it existed.
(It was then set to strict by default: `"confinement" property not specified: defaulting to "strict"`)

But then I also got:
`Issue detected while analyzing snapcraft.yaml: Cannot find definition for part 'desktop/qt5'. It may be a remote part, run "snapcraft update" to refresh the remote parts cache`

<https://launchpadlibrarian.net/271441376/buildlog_snap_ubuntu_xenial_amd64_qownnotes_BUILDING.txt.gz>

**Comment by dholbach** [comment]
I just asked the Launchpad team about this.

@kyrofa - Regarding the out-of-source build support, is there anything which might need a change in the qmake plugin?

**Comment by pbek** [comment]
thank you, @dholbach

**Comment by dholbach** [comment]
I filed https://bugs.launchpad.net/launchpad-buildd/+bug/1599786

**Comment by pbek** [comment]
Thank you @dholbach, I subscribed to it.

**Comment by kyrofa** [comment]
> @kyrofa - Regarding the out-of-source build support, is there anything which might need a change in the qmake plugin?

Yeah, PR is [here](https://github.com/snapcore/snapcraft/pull/633).

> I filed https://bugs.launchpad.net/launchpad-buildd/+bug/1599786

Worth pointing you to [this](https://github.com/snapcore/snapcraft/pull/617) as well-- snapcraft will do this automatically in the next release.

**Comment by pbek** [comment]
ah, nice!

**Comment by dholbach** [comment]
Thanks a lot @kyrofa

**Comment by pbek** [comment]
@kyrofa, I can confirm that I can now start applications from snaps under KDE Neon with snap 2.0.10, but I still have to use your local `qmake.py`. Building on Launchpad still doesn't work, same error: `Cannot find definition for part 'desktop/qt5'.`
But meanwhile I have uploaded a locally built qownnotes snap to the store. Now I'm waiting for the confirmation. :tada:

**Comment by kyrofa** [comment]
@pbek indeed, snapd and snapcraft are two separate products-- the new release of snapcraft (containing the updated qmake plugin and the fix for the LP builders) will be released in the next few days.

**Comment by pbek** [comment]
@kyrofa, thank you for informing me, I was hoping a `snapcraft update` would fetch directly from GitHub. ^_^

**Comment by pbek** [comment]
@dholbach, @kyrofa currently I get this error on Launchpad:

```
Running repo phase...
Cloning into 'qownnotes'...
Running pull phase...
Loaded local plugin for qmake
HTTPSConnectionPool(host='wiki.ubuntu.com', port=443): Max retries
exceeded with url: /Snappy/Parts?action=raw (Caused by
ProxyError('Cannot connect to proxy.', OSError('Tunnel connection
failed: 403 Forbidden',)))
Traceback (most recent call last):
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 194, in main
    builder.pull()
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 135, in pull
    env=env)
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 92, in run_build_command
    self.chroot(["/bin/sh", "-c", command], echo=echo)
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 66, in chroot
    "/usr/bin/sudo", "/usr/sbin/chroot", self.chroot_path] + args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
```

<https://launchpadlibrarian.net/272365528/buildlog_snap_ubuntu_xenial_amd64_qownnotes_BUILDING.txt.gz>

**Comment by pbek** [comment]
And does anyone know what is supposed to happen if a snap has the status `published` on <https://myapps.developer.ubuntu.com>? I can't find the snap anywhere to download publicly...

**Comment by dholbach** [comment]
Can you maybe give me the URL of your app in myapps and I'll see what I can do?

**Comment by dholbach** [comment]
Can you check if a channel is selected for the upload?

**Comment by pbek** [comment]
@dholbach, you are my hero. ^_^
<https://myapps.developer.ubuntu.com/dev/click-apps/5374/>

**Comment by pbek** [comment]
There is no channel selected for the upload at <https://myapps.developer.ubuntu.com/dev/click-apps/5374/configurations/>.

**Comment by dholbach** [comment]
... Downloading... :-)

**Comment by pbek** [comment]
I now manually selected the channel `Stable` (can that be done by `snapcraft upload`)

**Comment by dholbach** [comment]
That's going to be part of one of the next snapcraft releases: https://bugs.launchpad.net/snapcraft/+bug/1549211

**Comment by pbek** [comment]
Thank you, good to hear. Is it mandatory that the channel is set?

**Comment by dholbach** [comment]
Yes, I'll add a task for this bug for the store to set a sensible default in cases where it's not set (for whatever reason).

**Comment by pbek** [comment]
Thank you!

So do you know when/how/where the snap will be publicly available (now that I have set the channel manually)?

And you you know anything about the weird error at <https://launchpadlibrarian.net/272507287/buildlog_snap_ubuntu_xenial_i386_qownnotes_BUILDING.txt.gz>

**Comment by dholbach** [comment]
I just installed it using "snap find" and "snap install qownnotes" on Ubuntu 16.04 LTS. :-)

**Comment by dholbach** [comment]
The Launchpad fix is in progress right now.

**Comment by pbek** [comment]
Wow, you definitely are my hero now! :tada: 
So the next time I manually build a snap I just also need to set a channel at myapps, right?
But ultimately I want to build and release it with launchpad, I'm looking forward to that fix.

**Comment by dholbach** [comment]
I think it should land together with snapcraft 2.12.1.

**Comment by pbek** [comment]
Awesome!

by the way, can `qownnotes` now also be found at <https://apps.ubuntu.com/cat/search/?q=qownnotes&op=> and <https://uappexplorer.com/app/qownnotes>?

**Comment by dholbach** [comment]
apps.u.c is just for `.deb` packages - here's your snap: https://uappexplorer.com/app/qownnotes.pbek

**Comment by dholbach** [comment]
I'm not quite sure why the search on uappexplorer didn't find it. Maybe file a bug on https://github.com/bhdouglass/uappexplorer?

**Comment by pbek** [comment]
> https://uappexplorer.com/app/qownnotes.pbek

really awesome! :smile_cat: 

> bug

I now did at <https://github.com/bhdouglass/uappexplorer/issues/78>, thank you!

**Comment by dplanella** [comment]
@pbek looking at the conversation, I think this issue can be closed now, would you agree?

**Comment by pbek** [comment]
we do, thank you!

**Comment by pbek** [comment]
@dholbach, concerning building snaps on launchpad:
since the last update the `snapcraft update` seems to be done, but the build still fails:

```
Downloading parts list|                                                        
Parts 'desktop/qt5' and 'env' have the following file paths in common which have different contents:
usr/share/pkgconfig/xkeyboard-config.pc
Traceback (most recent call last):
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 194, in main
    builder.pull()
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 135, in pull
    env=env)
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 92, in run_build_command
    self.chroot(["/bin/sh", "-c", command], echo=echo)
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 66, in chroot
    "/usr/bin/sudo", "/usr/sbin/chroot", self.chroot_path] + args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/usr/bin/sudo', '/usr/sbin/chroot', '/home/buildd/build-SNAPBUILD-1600/chroot-autobuild', 'linux64', '/bin/sh', '-c', 'cd /build/qownnotes && env LANG=C.UTF-8 https_proxy=https://snap-proxy.launchpad.net:3128 http_proxy=http://snap-proxy.launchpad.net:3128 SNAPCRAFT_LOCAL_SOURCES=1 snapcraft pull']' returned non-zero exit status 1
```

<https://launchpadlibrarian.net/273098585/buildlog_snap_ubuntu_xenial_amd64_qownnotes_BUILDING.txt.gz>

**Comment by dholbach** [comment]
The issue you're mentioning depends on https://bugs.launchpad.net/launchpad-buildd/+bug/1599786

**Comment by pbek** [comment]
You mean as in "something broke while that issue was addressed"?
And now you filed https://bugs.launchpad.net/snapcraft/+bug/1603403...

**Comment by pbek** [comment]
After applying https://github.com/ubuntu/snappy-playpen/pull/178 to every part the snapcraft built, but after an install `qownnotes` just started as zombie process...

**Comment by dholbach** [comment]
Bugs 1603403 and 1599786 are quite separate things. I pinged the right people to take a look at them.

Can you give me a link to the changes you made, so I can take a look at it locally?

**Comment by pbek** [comment]
@dholbach, I created a feature branch for you with what I made:
https://code.launchpad.net/~pbek/qownnotes-snap/+git/qownnotes-snap/+ref/feature/snapcraft-2-12-1

**Comment by dholbach** [comment]
Try adding the `network-bind` plug - that should make it work.

**Comment by pbek** [comment]
Really, I just removed that because I have no network daemon. I will add it again and try. (why is it needed now?)

**Comment by pbek** [comment]
@dholbach, you are right, `network-bind` did the trick. Thanks a lot! Do you have any idea why `network-bind` is needed? And should not `desktop/qt5` together with `desktop-launch` somehow match the Qt theme with the Qt theme of the underlying system? They are not matched here on KDE Neon.

**Comment by dholbach** [comment]
I don't quite know why `network-bind` is needed - I seem to recall it was a transient thing and had to do with host look-ups(?).

Unfortunately I don't have a KDE Neon system to test this with. Do you know which files it looks for and can't find? I responded on the PR  #181 with a proposal on how to just use one part (and just one remote part).

**Comment by pbek** [comment]
Ok, thank you!

**Comment by pbek** [comment]
currently I have still a lot of issues with the snap..

- Qt theme (colors, widgets, icons, ...) does not match with native Qt theme under KDE Neon
- usage of the language files doesn't work
	-  the language is always the default language
- problems with UTF8 characters
	- see interface settings, language list
- cannot store notes to note folder
	- seems like it tried to write to an old revision's directory
- home directory changes with revision
	- e.g. `/home/omega/snap/qownnotes/13/ownCloud/Notes`
- snap is built in debug mode
	- should be release mode

**Comment by pbek** [comment]
@dholbach, I got around the home folder problem by trying to determine the real home folder of the user and suggest that folder, but the other troubles still exist

**Comment by pbek** [comment]
still some issues left with the `qownnotes` snap..

- Qt theme (colors, widgets, icons, ...) does not match with native Qt theme under KDE Neon
- usage of the language files doesn't work
	- the language is always the default language
	- are the language files not found?
- problems with UTF8 characters
	- see interface settings, language list or when typed in a note
	- Japanese or Chinese characters don't work
- debug information is logged in the build
	- I don't know how to get around that
