### ISSUE TITLE
Tyrant unleashed optimizer: drop 'x_' from plugin name

### ISSUE THREAD

**Issue by dplanella** [ubuntu/snappy-playpen#162]
Looking at Tyrant unleashed optimizer's snapcraft file, I see:

`plugin: x_toumakefixup`

While this works, we shouldn't be encouraging adding the `x_` prefix when declaring local plugins in `snapcraft.yaml`. The correct syntax should be:

`plugin: toumakefixup`

**Comment by dplanella** [comment]
@cpaelzer what do you think? ^

**Comment by cpaelzer** [comment]
I think back when adding this I followed some of "vlc/snapcraft.yaml:14:    plugin: x_vlcautotools" as an example. But I don't mind dropping the x_ at all and I see the reasoning you want to avoid the prefix becoming too common.

I checked if it still builds as of today, made this trivial change and checked again and finally submitted into PR 184.

Thank you for bringing it up!
