### ISSUE TITLE
Arabic support in the snap telegram package 

### ISSUE THREAD

**Issue by ibrahimd7** [ubuntu/snappy-playpen#194]
I installed telegram-sergiusens snap  app , and it ran very well .
But , All Arabic (recieved-sent) messages were blank and unreadable , and I think that it's a "fonts" issue 
Any suggestions ??
P.S : in the official linux telegram app I don't face such a problem

**Comment by liu-xiao-guo** [comment]
It is the same for Chinese even though I have tried to install the Chinese fonts packages in the snap.

**Comment by dholbach** [comment]
The Telegram snap is not part of the Snappy Playpen. If you refer to `telegram-sergiusens`, here's the package information: https://uappexplorer.com/app/telegram-sergiusens.sergiusens
