### ISSUE TITLE
python3 plugin cannot create hard link

### ISSUE THREAD

**Issue by sinzui** [ubuntu/snappy-playpen#232]
The python3 plugin fails on my xenial host during the parts phase.
    tar: ./usr/bin/python3.5: Cannot hard link to ‘./usr/bin/python3.5m’:

From snapcraft.yaml
parts:
    find-text:
        plugin: python3
        source: src

$ snapcraft clean
$ snapcraft snap
...
tar: ./usr/bin/python3.5: Cannot hard link to ‘./usr/bin/python3.5m’: Operation not permitted
tar: Exiting with failure status due to previous errors
dpkg-deb: error: subprocess tar returned error exit status 2
/home/curtis/Work/find-text/parts/find-text/ubuntu/download/python3.5-minimal_3.5.2-2~16.01_amd64.deb

$ ls /home/curtis/Work/find-text/parts/find-text/install/usr/bin/python*
python3.5m-config
python3-config
python3m
python3m-config
python3.5-config
python3.5m

**Comment by sinzui** [comment]
This is repeatable with the dcos-cli plugin.

**Comment by dholbach** [comment]
This looks more like a snapcraft issue. There was another dcos issue being discussed here: https://bugs.launchpad.net/snapcraft/+bug/1619104

**Comment by dholbach** [comment]
Does this work for you now?

**Comment by sinzui** [comment]
Sorry. It does not. I still see

Fetched 6,248 kB in 0s (0 B/s)                                                           
tar: ./usr/bin/python3.5: Cannot hard link to ‘./usr/bin/python3.5m’: Operation not permitted
tar: Exiting with failure status due to previous errors
dpkg-deb: error: subprocess tar returned error exit status 2

**Comment by dholbach** [comment]
Can we maybe move this bug to https://launchpad.net/snapcraft/+filebugs? The Playpen is mostly just about collecting best-practice examples.

**Comment by sinzui** [comment]
Done, https://bugs.launchpad.net/snapcraft/+bug/1625630

**Comment by dholbach** [comment]
Thanks a lot Curtis!
