### ISSUE TITLE
python2 plugin cannot find pip2

### ISSUE THREAD

**Issue by sinzui** [ubuntu/snappy-playpen#233]
python2 plugin cannot find pip2 during the parts phase building on xenial.
/home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip2 does not exist,
but these
/home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip
/home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip3
/home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip3.5

Note that my host does have pip 8.1.2 installed and it is pip2 as  the plugin assumes.
This failure happens after attempting to use the python3 plugin, which failed for a different reason.

Note I am surprised to see "Using /home/curtis/Work/DOTS/.local/lib/python2.7/site-packages".
Thinking this my download cache could be interfering with the snap, I unset the env var
    unset PIP_DOWNLOAD_CACHE
but it continues to show up.

From snapcraft.yaml
parts:
    find-text:
        plugin: python2
        source: src

$ snapcraft clean
$ snapcraft snap
...
Searching for pip
Best match: pip 8.1.2
Adding pip 8.1.2 to easy-install.pth file
Installing pip script to /home/curtis/Work/find-text/parts/find-text/install/usr/bin
Installing pip3.5 script to /home/curtis/Work/find-text/parts/find-text/install/usr/bin
Installing pip3 script to /home/curtis/Work/find-text/parts/find-text/install/usr/bin
Using /home/curtis/Work/DOTS/.local/lib/python2.7/site-packages
Processing dependencies for pip
Finished processing dependencies for pip
python2 /home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip2 install --global-option=build_ext --global-option=-I/home/curtis/Work/find-text/parts/find-text/install/usr/include/python2.7 --target /home/curtis/Work/find-text/parts/find-text/install/usr/lib/python2.7/site-packages .
python2: can't open file '/home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip2': [Errno 2] No such file or directory
Command '['/bin/sh', '/tmp/tmp9bezb1oa', 'python2', '/home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip2', 'install', '--global-option=build_ext', '--global-option=-I/home/curtis/Work/find-text/parts/find-text/install/usr/include/python2.7', '--target', '/home/curtis/Work/find-text/parts/find-text/install/usr/lib/python2.7/site-packages', '.']' returned non-zero exit status 2

**Comment by sinzui** [comment]
Moving my ~/.pip dir out of the way does not fix the issue:

python2: can't open file '/home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip2': [Errno 2] No such file or directory

$ ls /home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip*
/home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip
/home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip3
/home/curtis/Work/find-text/parts/find-text/install/usr/bin/pip3.5

**Comment by dholbach** [comment]
Does this work for you now?

**Comment by sinzui** [comment]
Yes this works thank you.
