### ISSUE TITLE
"after: [*]" broken?

### ISSUE THREAD

**Issue by LSenf** [ubuntu/snappy-playpen#248]
It seems that the line
`    after: [desktop/*]
`
makes snapcraft abort with
`'NoneType' object is not subscriptable
`
I tested this with my own attempt to build a gtk3 snap as well as with openttd (qt5) and some others from this repository.
My snapcraft version is 2.19 on ubuntu 16.04.
Is that syntax deprecated or is snapcraft broken?

**Comment by dholbach** [comment]
Can you try `[desktop-gtk3]` (with a `-`) for example?

**Comment by LSenf** [comment]
I tried both - and / for qt and gtk, they all give the same output.

**Comment by wandrewkeech** [comment]
just had a similar issue, try running `snapcraft update` and attempt again.

**Comment by LSenf** [comment]
Thank you, that solves it!
Maybe snapcraft should check for this and automatically update if a part is not found?

**Comment by dholbach** [comment]
Maybe you could file a bug at https://bugs.launchpad.net/snapcraft/+filebug about it? (Maybe this is what https://bugs.launchpad.net/snapcraft/+bug/1590934 is about?)
