### ISSUE TITLE
desktop-gtk2

### ISSUE THREAD

**Issue by rednoah** [ubuntu/snappy-playpen#269]
The `desktop-gtk2` part and all the other desktop parts have disappeared, breaking all the packages that depend on them.

```
$ snapcraft update && snapcraft search gtk
The parts cache is already up to date.
PART NAME       DESCRIPTION
gtkconf         This sets up the GTK environment for GTK-based projects
indicator-gtk2  Parts to show app-indicators for gtk2, gtk3, qt4 and qt5.
indicator-gtk3  Parts to show app-indicators for gtk2, gtk3, qt4 and qt5.
```

Have the desktop parts been replaced by something else? Or is this a bug?

**Comment by rednoah** [comment]
Thanks! I'll try again in a bit.

**Comment by didrocks** [comment]
confirmed that the revert worked. They are listed now!
We'll file a bug against the snapcraft importer parser.

Closing it, thanks for reporting this! :)
