### ISSUE TITLE
Fonts cache not generated in galculator

### ISSUE THREAD

**Issue by dholbach** [ubuntu/snappy-playpen#46]
In `galculator` the fonts cache needs to be generated an shipped.

**Comment by dholbach** [comment]
@flexiondotorg - I think this was done in the snap from the desktop team.

**Comment by seb128** [comment]
the wrapper has 
"#ln -sf $SNAP/usr/share/{fontconfig,fonts,fonts-*,themes} $XDG_DATA_HOME"

uncommenting that line should fix the issue (unsure why you commented it though, I guess it was copied from the gnome-calculator script ... was it any issue with it?)
