### ISSUE TITLE
GTK3 hello world app in snap

### ISSUE THREAD

**Issue by m-jch** [ubuntu/snappy-playpen#66]
Does anyone add GTK3 hello world app into snap?

https://git.gnome.org/browse/gtk+/plain/examples/hello-world.c

**Comment by dplanella** [comment]
This might be worth discussing on the snapcraft mailing list or on https://gitter.im/ubuntu/snappy-playpen, where someone can give you a hand getting started with snapcrafting it, which should be relatively simple. Thus closing the issue here.
