### ISSUE TITLE
Test should fail

### ISSUE THREAD

**Issue by dholbach** [ubuntu/snappy-playpen#8]
This test did not fail properly: https://travis-ci.org/ubuntu/snappy-playpen/builds/130977795

**Comment by didrocks** [comment]
The issue is that this branch wasn't rebased on master, which has the fix for ensuring the test fail (but it's the local ci-run script which is executed).

Btw, I'm going to add another check to the script, ensuring we have a README.md in the project!

**Comment by dholbach** [comment]
I just rebased on master, here's the test result: https://travis-ci.org/ubuntu/snappy-playpen/builds/131520108

**Comment by dholbach** [comment]
http://devopsreactions.tumblr.com/post/111166346362/bug-passes-qa

**Comment by didrocks** [comment]
ok ok, I'll have a look :) It's what I am, too kind with you guys, green flags everywhere \o/

**Comment by dholbach** [comment]
Good work! :+1:
