### ISSUE TITLE
VLC 'Permission denied'

### ISSUE THREAD

**Issue by Ads20000** [ubuntu/snappy-playpen#80]
I am using Ubuntu Yakkety.

```
$ snap --version
snap  2.0.9+16.10
snapd 2.0.9+16.10 (series 16)
```

```
$ snap list
Name         Version               Rev  Developer  Notes
ubuntu-core  16.04+20160531.11-56  122  canonical  -
vlc          daily                 5    caldav     -
```

```
$ vlc
/usr/bin/ubuntu-core-launcher: 3: exec: /usr/lib/snap-confine/snap-confine: Permission denied
```

I'm using the Edge channel for VLC. Do I have to explicitly use --devmode when installing an Edge or Beta channel Snap? Or should it work anyway? Given that the standard version of this VLC Snap is 'daily', maybe it doesn't matter in this case anyway.

My guess is that the VLC Snap isn't being given enough permissions.

```
$ snap interfaces
Slot                 Plug
:cups-control        -
:firewall-control    -
:gsettings           -
:home                vlc
:locale-control      -
:log-observe         -
:mount-observe       -
:network             vlc
:network-bind        -
:network-control     -
:network-manager     -
:network-observe     -
:opengl              vlc
:pulseaudio          vlc
:snapd-control       -
:system-observe      -
:timeserver-control  -
:timezone-control    -
:unity7              vlc
:x11                 -
```

What other permissions does it need? This should be a quick fix if that can be figured out.

I don't _think_ this issue is related to #78 but maybe there's a way I can get more verbose output to find out.

**Comment by caldav** [comment]
Do other snaps work? Eg. krita?

**Comment by Ads20000** [comment]
Ah, it doesn't sorry, same error, what do I do to fix this? Shouldn't installing applications in Snappy just work 'out of the box' anyway? :/

**Comment by dplanella** [comment]
Closing the issue as it's not directly related to VLC in the playpen and it's been reported in snappy upstream instead. If you feel you need to follow it up here instead, please feel free to reopen. Thanks!
